using System.Collections.Generic;

namespace VVG.Web.Models;

/// <summary>
/// The top-level structure of blog-index.json — generated by the Indexer tool
/// and loaded by the Blog page to populate listings, tag filters, and year
/// archives without needing to read every Markdown file individually.
/// </summary>
public class BlogIndex
{
    /// <summary>All blog posts sorted by date (newest first).</summary>
    public BlogPost[]? Posts { get; set; }

    /// <summary>
    /// Count of posts per tag.
    /// Example: { "Technology": 5, "Business": 3, "Marketing": 2 }
    /// </summary>
    public Dictionary<string, int>? TagsSummary { get; set; }

    /// <summary>
    /// Count of posts per publication year.
    /// Example: { "2025": 8, "2026": 4 }
    /// </summary>
    public Dictionary<string, int>? YearsSummary { get; set; }
}
